from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Optional, List

@dataclass
class Department:
    # ID is auto-generated by database - never set manually
    id: Optional[int] = field(default=None, init=False, repr=False)
    name: str = ""
    # created_at is auto-generated by database with default value
    created_at: Optional[str] = field(default=None, init=False)
